version: '3'
services:
  easyproxy:
    image: justsml/easy-proxy:latest
    container_name: easyproxy
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      - PROXY_USERNAME=admin
      - PROXY_PASSWORD=changeme
      - PROXY_HOST=your-domain
